version: '3.8'

services:
  mongo:
    image: mongo
    ports:
    - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: daniel_mongo_user
      MONGO_INITDB_ROOT_PASSWORD: Edaniel7
      MONGO_INITDB_DATABASE: the_database
    volumes:
    - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    - ./mongo_data:/data/db